<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ML7ORHO5" failures="1" tests="1" name="DemoBlazeTest(failed)" time="6.947" errors="0" timestamp="2023-08-11T22:51:33 IST">
  <testcase classname="testCases.TC_001_CheckRegistration" name="test_account_Registration" time="1.513">
    <failure type="java.lang.AssertionError" message="expected [Sign up successful] but found [Sign up successful.]">
      <![CDATA[java.lang.AssertionError: expected [Sign up successful] but found [Sign up successful.]
at testCases.TC_001_CheckRegistration.test_account_Registration(TC_001_CheckRegistration.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test_account_Registration -->
</testsuite> <!-- DemoBlazeTest(failed) -->
